version: '3.8'
services:
  go-scheduler:
    container_name: go-scheduler
    image: jonioliveira/go-scheduler:local
    environment:
      GOCACHE: /.cache/go-build
      GOLANGCI_LINT_CACHE: /.cache/golangci-lint
    command:
      - make
      - migrate
      - shell-go-generate
      - shell-go-run
    ports:
      - "${PORT:-8081}:8081"
    volumes:
      - $PROJECT_ROOT:/opt/app/
      - /opt/app/bin
      - $PROJECT_ROOT/.cache/:/.cache/
    depends_on: 
      - postgres
  
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Postgres2019!}
    ports:
      - "${POSTGRES_PORT:-5051}:80"
    volumes:
      - $PROJECT_ROOT/data/db:/var/lib/postgresql/data 
      
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - $PROJECT_ROOT/data/pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres

